-- MySQL Script generated by MySQL Workbench
-- Tue Oct 11 22:29:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`agência`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`agência` ;

CREATE TABLE IF NOT EXISTS `mydb`.`agência` (
  `name_agência` INT NOT NULL,
  `cidade_agência` VARCHAR(45) NOT NULL,
  `ativo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name_agência`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`funcionário` ;

CREATE TABLE IF NOT EXISTS `mydb`.`funcionário` (
  `id_funcionário` INT NOT NULL,
  `nome_funcionário` VARCHAR(45) NOT NULL,
  `número_telefone` VARCHAR(45) NOT NULL,
  `data_admissão` VARCHAR(45) NOT NULL,
  `tempo_serviço` VARCHAR(45) NOT NULL,
  `funcionário_id_funcionário` INT NOT NULL,
  PRIMARY KEY (`id_funcionário`),
  INDEX `fk_funcionário_funcionário1_idx` (`funcionário_id_funcionário` ASC) VISIBLE,
  CONSTRAINT `fk_funcionário_funcionário1`
    FOREIGN KEY (`funcionário_id_funcionário`)
    REFERENCES `mydb`.`funcionário` (`id_funcionário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `rua_cliente` VARCHAR(45) NOT NULL,
  `cidade_cliente` VARCHAR(45) NOT NULL,
  `id_funcionário` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_funcionário1_idx` (`id_funcionário` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_funcionário1`
    FOREIGN KEY (`id_funcionário`)
    REFERENCES `mydb`.`funcionário` (`id_funcionário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dependente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`dependente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`dependente` (
  `nome_dependente` INT NOT NULL,
  `id_funcionário` INT NOT NULL,
  PRIMARY KEY (`nome_dependente`, `id_funcionário`),
  INDEX `fk_dependente_funcionário_idx` (`id_funcionário` ASC) VISIBLE,
  CONSTRAINT `fk_dependente_funcionário`
    FOREIGN KEY (`id_funcionário`)
    REFERENCES `mydb`.`funcionário` (`id_funcionário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empréstimo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`empréstimo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`empréstimo` (
  `quantia` INT NOT NULL,
  `número_empréstimo` VARCHAR(45) NOT NULL,
  `id_cliente` INT NOT NULL,
  `name_agência` INT NOT NULL,
  INDEX `fk_empréstimo_cliente1_idx` (`id_cliente` ASC) VISIBLE,
  PRIMARY KEY (`número_empréstimo`),
  INDEX `fk_empréstimo_agência1_idx` (`name_agência` ASC) VISIBLE,
  CONSTRAINT `fk_empréstimo_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empréstimo_agência1`
    FOREIGN KEY (`name_agência`)
    REFERENCES `mydb`.`agência` (`name_agência`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `número_pagamento` INT NOT NULL,
  `data_pagamento` VARCHAR(45) NOT NULL,
  `quantia_pagamento` VARCHAR(45) NOT NULL,
  `número_empréstimo` VARCHAR(45) NOT NULL,
  INDEX `fk_pagamento_empréstimo1_idx` (`número_empréstimo` ASC) VISIBLE,
  PRIMARY KEY (`número_empréstimo`, `número_pagamento`),
  CONSTRAINT `fk_pagamento_empréstimo1`
    FOREIGN KEY (`número_empréstimo`)
    REFERENCES `mydb`.`empréstimo` (`número_empréstimo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`conta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`conta` (
  `número_conta` INT NOT NULL,
  `saldo` VARCHAR(45) NOT NULL,
  `tipo_conta` VARCHAR(45) NOT NULL,
  `name_agência` INT NOT NULL,
  PRIMARY KEY (`número_conta`),
  INDEX `fk_conta_agência1_idx` (`name_agência` ASC) VISIBLE,
  CONSTRAINT `fk_conta_agência1`
    FOREIGN KEY (`name_agência`)
    REFERENCES `mydb`.`agência` (`name_agência`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conta_poupança`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`conta_poupança` ;

CREATE TABLE IF NOT EXISTS `mydb`.`conta_poupança` (
  `taxa_juros` INT NOT NULL,
  `número_conta` INT NOT NULL,
  PRIMARY KEY (`número_conta`),
  CONSTRAINT `fk_conta_poupança_conta1`
    FOREIGN KEY (`número_conta`)
    REFERENCES `mydb`.`conta` (`número_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conta_corrente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`conta_corrente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`conta_corrente` (
  `quantia_saque_decoberto` INT NOT NULL,
  `número_conta` INT NOT NULL,
  PRIMARY KEY (`número_conta`),
  CONSTRAINT `fk_conta_corrente_conta1`
    FOREIGN KEY (`número_conta`)
    REFERENCES `mydb`.`conta` (`número_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`depositante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`depositante` ;

CREATE TABLE IF NOT EXISTS `mydb`.`depositante` (
  `id_cliente` INT NOT NULL,
  `número_conta` INT NOT NULL,
  `data_acesso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`, `número_conta`),
  INDEX `fk_cliente_has_conta_conta1_idx` (`número_conta` ASC) VISIBLE,
  INDEX `fk_cliente_has_conta_cliente1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_conta_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_conta_conta1`
    FOREIGN KEY (`número_conta`)
    REFERENCES `mydb`.`conta` (`número_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
